FROM alpine:latest
ENV APPVERSION=1.10
LABEL VERSION="redix-${APPVERSION}"
LABEL EMAIL="1141519465@qq.com"
LABEL AUTHOR="dalongrong"
WORKDIR /app
COPY redix /usr/local/bin/
ENV ENGINE=leveldb
ENV STORAGE=./redix-data
ENV RESP=:6380
ENV REST=:7090
ENV WORKERS=4
EXPOSE 6380 7090
ENV PATH=$PATH:/usr/local/bin
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh && chmod +x /usr/local/bin/redix
ENTRYPOINT ["./entrypoint.sh"]